// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/kart-io/kart/example/base-example/app"
)

// Injectors from wire.go:

func wireApp(engine *gin.Engine) (*app.App, func(), error) {
	serverConfig := app.NewConfig()
	appApp, err := app.NewHttpSever(serverConfig, engine)
	if err != nil {
		return nil, nil, err
	}
	return appApp, func() {
	}, nil
}
